// lib/scenario-files.js
//
// Scenario modules on disk: where they live, how a name is validated, and how a scenario
// built in memory becomes a file the ordinary loader (scripts/load-scenario.js) can require.
// ---------------------------------------------------------------------------

const fs   = require('fs');
const path = require('path');

const SCENARIOS_DIR = path.join(__dirname, '..', 'scripts', 'scenarios');

// Scenario names become file names and shell arguments, so they are kept to a safe alphabet.
const SAFE_NAME = /^[A-Za-z0-9_-]{1,80}$/;

function scenarioPath(name) {
  if (!SAFE_NAME.test(name)) throw new RangeError(`invalid scenario name "${name}"`);
  return path.join(SCENARIOS_DIR, `${name}.js`);
}

/**
 * Write `{ meta, entities, medicalDetails }` as scripts/scenarios/<meta.name>.js.
 * Generated files are git-ignored (random_*.js): they are reproducible from their seed.
 */
function writeScenarioModule(scenario) {
  const file = scenarioPath(scenario.meta.name);
  const body = [
    `// ${path.relative(path.join(__dirname, '..'), file)}`,
    '//',
    `// Generated by ${scenario.meta.generated?.by || 'a scenario generator'}. Do not edit:`,
    '// regenerate it from the seed in meta.generated instead.',
    '',
    `const scenario = ${JSON.stringify(scenario, null, 2)};`,
    '',
    'module.exports = scenario;',
    '',
  ].join('\n');
  fs.writeFileSync(file, body, 'utf-8');
  return file;
}

module.exports = { SCENARIOS_DIR, scenarioPath, writeScenarioModule };
